
# Este archivo ya no es necesario para el despliegue del gateway si se usa una VM.
# Se deja como referencia o para el despliegue del frontend de Next.js en el futuro.
# Para desplegar el gateway en la VM, sigue las instrucciones de creación de VM con el startup-script.
steps:
  # Despliegue del Frontend (Ejemplo, actualmente no configurado)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: 'Install Frontend Dependencies'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    id: 'Build Frontend'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'app'
      - 'deploy'
      - '--project=$PROJECT_ID'
    id: 'Deploy Frontend to App Engine'

substitutions:
  _SERVICE_NAME: servidormanito-frontend
  _DEPLOY_REGION: europe-west1

options:
  logging: CLOUD_LOGGING_ONLY
